files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /fastlane/metadata/android/en-US/*.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
